[project]
name = "testbed"
version = "0.1.0"
description = "Python dashboard for the testbed"
readme = "README.md"
authors = [
    { name="Kuravi H", email="kuravih@gmail.com" },
]
requires-python = ">=3.12"
dependencies = [
    "toml>=0.10.2",
    "numpy>=2.4.0",
    "matplotlib>=3.10.8",
    "astropy>=7.2.0",
    "pyzmq>=27.1.0",
    "pyside6>=6.10.1",
    "cloudpickle>=3.1.2"
]

[dependency-groups]
dev = [
    "black>=25.12.0",
    "isort>=7.0.0",
    "pylint>=4.0.4",
    "pytest>=8.4.2",
]

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[tool.mypy]
check_untyped_defs = true