[project]
name = "testbed"
version = "0.0.1"
description = "Python dashboard for the testbed"
authors = [
  { name="Kuravi H", email="kuravih@gmail.com" },
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.8"
dependencies = ["toml", "numpy", "matplotlib", "astropy", "pyzmq", "pyside6", "pykato @ git+https://github.com/kuravih/pykato.git"]